lkarea.o: lkarea.c ../aslink.h
lkihx.o: lkihx.c ../aslink.h
lk_readnl.o: ../lk_readnl.c ../lk_readnl.h
lkaomf51.o: ../lkaomf51.c ../aslink.h
lkar.o: ../lkar.c ../aslink.h ../lklibr.h ../lkrel.h ../lkar.h
lkdata.o: ../lkdata.c ../aslink.h
lkelf.o: ../lkelf.c ../asxxxx_config.h ../aslink.h
lkeval.o: ../lkeval.c ../aslink.h
lkgb.o: ../lkgb.c ../sdld.h ../aslink.h
lkhead.o: ../lkhead.c ../aslink.h
lklex.o: ../lklex.c ../aslink.h
lklib.o: ../lklib.c ../lk_readnl.h ../aslink.h ../lklibr.h ../lkrel.h
lklibr.o: ../lklibr.c ../aslink.h ../lkrel.h ../lklibr.h
lklist.o: ../lklist.c ../aslink.h
lkmain.o: ../lkmain.c ../sdld.h ../aslink.h
lkmem.o: ../lkmem.c ../sdld.h ../aslink.h
lknoice.o: ../lknoice.c ../aslink.h
lkrel.o: ../lkrel.c ../lk_readnl.h ../aslink.h ../lkrel.h
lkrloc.o: ../lkrloc.c ../sdld.h ../aslink.h
lks19.o: ../lks19.c ../aslink.h
lksdcclib.o: ../lksdcclib.c ../lk_readnl.h ../aslink.h ../lklibr.h \
  ../lkrel.h
lksym.o: ../lksym.c ../aslink.h
sdld.o: ../sdld.c ../sdld.h
strcmpi.o: ../../asxxsrc/strcmpi.c
